### ISSUE TITLE
Translate button in chat mode is not clickable

### ISSUE THREAD

**Issue by andreaskoenig** [justarrived/just-match-frontend#266] opened 2016-05-09 16:59 UTC
__Description__ TEAM 5

I cannot change language in the chat 

__Severity__:

_Chose one of the below:_

* Can not perform action

__URL__: http://justarrived.dev-machine.com/#/arriver/job/115

__Error message__: The error message displayed, if any.

__Role__: Company user / user / Not logged in

__How to recreate it__

1. Goto ...
2. Click ...
3.

__What happend__
i could not change language

__Expected outcome__

__Browser (check what browser you're running at https://whatbrowser.org)__: Chrome 
<img width="1280" alt="skarmavbild 2016-05-09 kl 18 55 22" src="https://cloud.githubusercontent.com/assets/19269861/15120877/16d9d574-1618-11e6-9513-b2d866ef414d.png">

__Screenshot__

Take a screenshot of the error.

**Comment by chris-sedp** [comment] 2016-05-17 05:15
Duplicate of https://github.com/justarrived/just-match-frontend/issues/156

Closing  this one

**Closed by chris-sedp** 2016-05-17 05:15 UTC
Labels: bug
